[package]
name = "json-over-dns"
version = "0.1.0"
authors = ["Michael Hoy <mjh@mjhoy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
